apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo
  region: us-east-2

managedNodeGroups:
  - name: demo-public-ingress
    instanceType: "t2.medium"
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
    labels:
      tier: public-ingress
    subnets:
      - [public subnet a]
      - [public subnet b]
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true