apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-default
  labels:
    app: ENVVAR_APP
  name: ENVVAR_APP
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ENVVAR_APP
  template:
    metadata:
      labels:
         app: ENVVAR_APP
    spec:
      terminationGracePeriodSeconds: ENVVAR_TERMINATION_GRACE_PERIOD_SECONDS
      containers:
        - name: ENVVAR_APP
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
            - name: https
              protocol: TCP
              containerPort: 443
            - name: https-alt
              protocol: TCP
              containerPort: 4443
          resources:
            requests:
              cpu: ENVVAR_RESOURCES_REQUESTS_CPU
              memory: ENVVAR_RESOURCES_REQUESTS_MEMORY
          env:
            - name: _STAGE
              value: ENVVAR__STAGE
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: _REGION
              value: ENVVAR__REGION
            - name: _ACCOUNT
              value: "ENVVAR__ACCOUNT"
            - name: ASPNETCORE_HTTP_PORTS
              value: "80"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 40"]
      nodeSelector:
        tier: public-services
---
apiVersion: v1
kind: Service
metadata:
  namespace: demo-default
  name: ENVVAR_APP
  labels:
    app: ENVVAR_APP
spec:
  selector:
    app: ENVVAR_APP
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
    - name: https-alt
      protocol: TCP
      port: 4443
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: demo-default
  name: ENVVAR_APP
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ENVVAR_APP
  minReplicas: ENVVAR_MIN_REPLICAS
  maxReplicas: ENVVAR_MAX_REPLICAS
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: ENVVAR_UTILIZATION_CPU_AVERAGE
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ENVVAR_APP
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ENVVAR_APP